#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = 'win2012r2chef'
  config.vm.box_url = '/Users/spage/Documents/saheb/Work/Boxes/win2012_r2_chef12_11_18.box'
  config.vm.guest = :windows

  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
  config.vm.communicator = "winrm"
  config.winrm.timeout = 24000
  config.winrm.max_tries = 20

  config.winrm.host = '127.0.0.1'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'

  config.vm.provision :chef_solo do |chef|
    chef.log_level         = :debug
    chef.cookbooks_path = [".."]
    chef.add_recipe("chocolatey")
    chef.add_recipe("dotnetframework::add")

    chef.json = { "workorder": { "rfcCi": { "ciAttributes": { "dotnet_framework_version": "dotnet4.5.2",  "chocolatey_package_source": "https://chocolatey.org/api/v2/"  } } } }
  end

end
