FROM <%= @image_id %>
ENV container docker

<% if @image_id =~ /redhat|centos|fedora/ %>
# redhat, centos, fedora
RUN yum -y update; yum clean all
RUN yum -y install rsyslog openssh-server
RUN yum -y install sudo rsync file make gcc glibc-devel libgcc ruby ruby-libs ruby-devel libxml2-devel libxslt-devel ruby-rdoc rubygems perl
RUN yum -y install ntp which tar zip unzip sysstat autoconf automake libtool bison bind bind-utils java-1.6.0-openjdk net-tools moreutils nc
RUN echo "NETWORKING=yes" > /etc/sysconfig/network
RUN echo "HOSTNAME=<%= @image_name %>" >> /etc/sysconfig/network

<% elsif @image_id =~ /suse/ %>
# suse
RUN zypper -q --gpg-auto-import-keys -n ref
RUN zypper -q -n update
RUN zypper -q -n in systemd netcfg rsyslog openssh openssl
RUN zypper -q -n in sudo rsync file make gcc glibc-devel ruby ruby-devel rubygems libxml2-devel libxslt-devel perl
RUN gem update --system 1.8.25
RUN zypper -q -n in rubygem-yajl-ruby
RUN zypper -q -n in ntp which tar zip unzip sysstat autoconf automake libtool bison bind bind-utils java-1.7.0-openjdk netcat
RUN zypper -q -n in nagios nagios-devel lsof
RUN echo "HOSTNAME=<%= @image_name %>" > /etc/HOSTNAME

<% elsif @image_id =~ /ubuntu|debian/ %>
# debian, ubuntu
RUN apt-get -y update
RUN apt-get -y install rsyslog openssh-server rsync
<% end %>

ADD authorized_keys /root/.ssh/authorized_keys
ADD init /usr/sbin/init
EXPOSE 22
CMD  ["/usr/sbin/init"]
