#!/usr/bin/perl
###################################################################
# check_squid is developped with GPL Licence 2.0
#
# GPL License: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
#
# Developped by : Cyril Feraudet
#
###################################################################
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#    For information : cyril@feraudet.com
####################################################################

my $VERSION = "1.0";

$|;
use Nagios::Plugin;
# todo : use strict;


$np = Nagios::Plugin->new(usage => "Usage: %s [ -v|--verbose ] [ -H <host> ] [ -d <data> ] [ -p <port> ] [ -t <timeout>] [ -c <threshold> ] [ -w <threshold> ]", version => $VERSION);

$np->add_arg(
	spec => 'host|H=s',
	help => "-H, --host=<hostname>\n"
	. "	Name of the proxy to check (default: localhost)",
	required => 0
);

$np->add_arg( # Connections Cache Resources Memory FileDescriptors
	spec => 'data|d=s',
	help => "-d, --data=<data>\n"
	. "	Optional data to fetch (default: Connections)"
	. "	available data : Connections Cache Resources Memory FileDescriptors",
	required => 0
);

$np->add_arg(
	spec => 'port|p=i',
	help => "-p, --port=<port>\n"
	. "	Optional port number (default: 3128)",
	required => 0
);

$np->add_arg(
	spec => 'user|U=s',
	help => "-U, --user=<user>\n"
	. "	Optional WWW user (default: root)",
	required => 0
);

$np->add_arg(
	spec => 'password|W=s',
	help => "-W, --password=<password>\n"
	. "	Optional WWW password",
	required => 0
);

$np->add_arg(
	spec => 'warning|w=s',
	help => "-w, --warning=THRESHOLD\n"
	. "	Warning threshold. See\n"
	. "	http://nagiosplug.sourceforge.net/developer-guidelines.html#THRESHOLDFORMAT\n"
	. '	for the threshold format.',
	required => 0,
);

$np->add_arg(
	spec => 'critical|c=s',
	help => "-c, --critical=THRESHOLD\n"
	. "	Critical threshold. See\n"
	. "	http://nagiosplug.sourceforge.net/developer-guidelines.html#THRESHOLDFORMAT\n"
	. '	for the threshold format.',
	required => 0,
);

$np->add_arg(
	spec => 'squidclient|s=s',
	help => "-s, --squidclient=<squidclient_path>\n"
	. "	Path of squidclient (default: /usr/sbin/squidclient)",
	required => 0,
);

$np->getopts;

my $host = $np->opts->host;
my $port = $np->opts->port;
my $data = $np->opts->data;
my $user = $np->opts->user;
my $password = $np->opts->password;
my $critical = $np->opts->critical;
my $warning = $np->opts->warning;
my $squidclient = $np->opts->squidclient;


$host = 'localhost' if (!defined($host) or $host eq '');
$port = 3128 if (!defined($port) or $port eq '');
$data = 'Connections' if (!defined($data) or $data eq '');
$user = 'root' if (!defined($user) or $user eq '');
$password = '' if (!defined($password));
$critical = undef if (defined($critical) and $critical eq '');
$warning = undef if (defined($warning) and $warning eq '');
$squidclient = '/usr/sbin/squidclient' if (!defined($squidclient) or $squidclient eq '');

$np->set_thresholds(critical => $critical, warning => $warning);

@exec = ("-h", "\Q$host", "-p", "\Q$port", "-U", "\Q$user", "-W", "\Q$password", "mgr:info");

@result = `$squidclient @exec`;


my $fd_available;
my $fd_used;
my $memory_available;
my $memory_used;
my $connection_nbclient;
my $connection_nbicpreceived;
my $connection_nbicpsent;
my $connection_nbicpqueued;
my $cache_requesthitratio5;
my $cache_requesthitratio60;
my $cache_bytehitratio5;
my $cache_bytehitratio60;
for my $line (@result)
{
	chomp($line);
	$line =~ /\s+CPU Usage:\s+([0-9\.]+)%/ and $resource_cpu5s = $1;
	$line =~ /\s+CPU Usage, 5 minute avg:\s+([0-9\.]+)%/ and $resource_cpu5m = $1;
	$line =~ /\s+CPU Usage, 60 minute avg:\s+([0-9\.]+)%/ and $resource_cpu60m = $1;
	$line =~ /\s+Total in use:\s+([0-9]+)/ and $memory_used = $1;
	$line =~ /\s+Total size:\s+([0-9]+)/ and $memory_available = $1;
	$line =~ /\s+Maximum number of file descriptors:\s+([0-9]+)/ and $fd_available = $1;
	$line =~ /\s+Number of file desc currently in use:\s+([0-9]+)/ and $fd_used = $1;
}

if($data =~ /Connections/i)  # Connections Cache Resources Memory FileDescriptors
{
	$np->add_perfdata( label => "HTTP requests", value => $connection_nbhttpreceived, uom => "c");
	$np->add_perfdata( label => "sent ICP requests", value => $connection_nbicpsent, uom => "c");
	$np->add_perfdata( label => "received ICP requests", value => $connection_nbicpreceived, uom => "c");
	$np->nagios_exit('OK', "Squid have $connection_nbclient clients and $connection_nbicpqueued ICP requests queued");
}
if($data =~ /Cache/i)
{
	$np->add_perfdata( label => "Requests Hit Ratio 5min", value => $cache_requesthitratio5, uom => "%");
	$np->add_perfdata( label => "Requests Hit Ratio 60min", value => $cache_requesthitratio60, uom => "%");
	$np->add_perfdata( label => "Byte Hit Ratio 5min", value => $cache_bytehitratio5, uom => "%");
	$np->add_perfdata( label => "Byte Hit Ratio 60min", value => $cache_bytehitratio60, uom => "%");
	$np->nagios_exit('OK', "Requests Hit Ratio 5min: $cache_requesthitratio5, Requests Hit Ratio 60min: $cache_requesthitratio60, Byte Hit Ratio 5min: $cache_bytehitratio5, Byte Hit Ratio 60min: $cache_bytehitratio60");
}
if($data =~ /Resources/i)
{
	$np->add_perfdata( label => "CPU used 5s", value => $resource_cpu5s, uom => "%");
	$np->add_perfdata( label => "CPU used 5m", value => $resource_cpu5m, uom => "%");
	$np->add_perfdata( label => "CPU used 60m", value => $resource_cpu60m, uom => "%");
	$np->nagios_exit('OK', "CPU used 5s: $resource_cpu5s, CPU used 5m: $resource_cpu5m, CPU used 60m: $resource_cpu60m");
}
if($data =~ /Memory/i)
{
	my $t = Nagios::Plugin::Threshold->set_thresholds(warning  => $warning, critical => $critical);
	$np->add_perfdata( label => "Memory used", value => $memory_used, uom => "KB", threshold => $t);
	$np->add_perfdata( label => "Memory available", value => $memory_available, uom => "KB");
	$np->nagios_exit($np->check_threshold($memory_used), "Squid use $memory_used KB of memory");
}
if($data =~ /FileDescriptors/i)
{
	my $t = Nagios::Plugin::Threshold->set_thresholds(warning  => $warning, critical => $critical);
	$np->add_perfdata( label => "Max FD", value => $fd_available);
	$np->add_perfdata( label => "Cur FD", value => $fd_used, threshold => $t);
	$np->nagios_exit($np->check_threshold($fd_used), 'Squid work fine.');
}

