#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = 'win2012r2chef121118'
  config.vm.guest = :windows

  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
  config.vm.communicator = "winrm"
  config.winrm.timeout = 24000
  config.winrm.max_tries = 20

  config.winrm.host = '127.0.0.1'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'

  config.vm.provision :chef_solo do |chef|
    chef.log_level      = :info
    chef.cookbooks_path = [".."]

    chef.add_recipe("iis-website::add")

    chef.json = {
                	"iis-website": {
                		"app_pool_name": "test",
                		"site_name": "test",
                		"runtime_version": "v4.0",
                		"identity_type": "ApplicationPoolIdentity",
                		"binding_type": "http",
                		"binding_port": 82,
                		"physical_path": "c:\\test"
                }
}
  end

end
